### ISSUE TITLE
Missing Prefeb in Character Scene

### ISSUE THREAD

**Issue by devangkantharia** [keijiro/TimelineParticleControl#1]
I imported your project, but the character scene is broken. There is a missing prefeb as well as few other linkages. Could you please add unitypackage file so that I can import and explore the possibilities.

**Comment by keijiro** [comment]
I'm pretty sure that this repository is built in a self-contained fashion. If you have problems with using git, I'd recommend trying the following zip link.

https://github.com/keijiro/TimelineParticleControl/archive/master.zip

**Comment by keijiro** [comment]
I'm closing this ticket. Please feel free to reopen for further questions.

**Comment by devangkantharia** [comment]
Thank you for your reply sir. I found the issue. I am importing your project which is developed in unity version 2018.2.0 to my current PC unity version 2017.3.1f1, and it breaks the prefab. Now as I imported in latest version 2018.2.5f1, it is working absolutely fine.
