### ISSUE TITLE
Add Burst control feature

### ISSUE THREAD

**Issue by marcmantra** [keijiro/TimelineParticleControl#3]
Hi,

I'm using your scripts to control multiple particles systems and create a big choreography. If particles systems use rateOverTime or rateOverDistance goes like charm but when I use one or more bursts the challenge starts. I try to learn and apply a solution using the [Unity Blog example](https://blogs.unity3d.com/2018/09/05/extending-timeline-a-practical-guide/)
My result seems to go wrong because it's not active on Timeline and I don't know how to adapt this on your code. I attach my code using unity example to show you an example.

Your script as you said solve many important point and maybe it's possible to update to control bursts?

Thanks in advance,

[Track_ParticleSystemControlTrack.txt](https://github.com/keijiro/TimelineParticleControl/files/3340199/Track_ParticleSystemControlTrack.txt)
[Track_ParticleSystemControlAsset.txt](https://github.com/keijiro/TimelineParticleControl/files/3340200/Track_ParticleSystemControlAsset.txt)
[Track_ParticleSystemControlBehaviour.txt](https://github.com/keijiro/TimelineParticleControl/files/3340201/Track_ParticleSystemControlBehaviour.txt)

**Comment by keijiro** [comment]
Timeline Clips only work well for controlling values that change in a specific time period. Burst is not a thing like that. It's more like events or triggers, not changing values.

I'd recommend using Timeline Signals instead. You can invoke any event at some points on a timeline.

https://blogs.unity3d.com/2019/05/21/how-to-use-timeline-signals/

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.

**Comment by marcmantra** [comment]
Thanks Keijiro! After you told me it can't be possible, I solve it adjusting duration, many particles on emission by time and limit it by 1. Same result, different way seems.
