### ISSUE TITLE
Unity 2019.3 support

### ISSUE THREAD

**Issue by skjalgsm** [keijiro/TimelineParticleControl#4]
Timeline has been moved into its own package now so it would be nice to have it added as a dependency. Maybe in a upm_2019_3 branch?

> Library/PackageCache/jp.keijiro.klak.timeline.particle-system-control@2806049fc31f466c1d619dadf67935b9856358c5/Runtime/ParticleSystemControlClip.cs(6,19): error CS0234: The type or namespace name 'Timeline' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)

**Comment by cAyou** [comment]
Any update on this? I will take a look myself, if it's not too hard.

**Comment by keijiro** [comment]
fixed https://github.com/keijiro/TimelineParticleControl/commit/1fd258838bc8e45b6d6c66b70c65a18e006d341a

**Comment by cAyou** [comment]
> fixed [1fd2588](https://github.com/keijiro/TimelineParticleControl/commit/1fd258838bc8e45b6d6c66b70c65a18e006d341a)

Thanks!! It was super quick.
